language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar --prefer-source --dev install
  - cp phpunit.xml.dist phpunit.xml

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit -c ./ --exclude-group functional

